# Generated by Django 6.0.1 on 2026-01-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_passwordresetcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
