# Generated by Django 6.0.1 on 2026-01-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_userprofile_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='added_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
