# Generated by Django 6.0.1 on 2026-01-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userprofile_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('On Trip', 'On Trip'), ('Off Duty', 'Off Duty')], default='Available', max_length=20),
        ),
    ]
