# Generated by Django 6.0.1 on 2026-01-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userprofile_is_driver_userprofile_license_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_log',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
