# Generated by Django 6.0.1 on 2026-01-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_userprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='added_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
