# Generated by Django 6.0.1 on 2026-01-26 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='status',
        ),
    ]
