# Generated by Django 6.0.1 on 2026-01-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('profile_picture', models.ImageField(blank=True, upload_to='driver_pictures')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On Trip', 'On Trip'), ('Off Duty', 'Off Duty')], default='Available', max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
        ),
    ]
