# Generated by Django 6.0.1 on 2026-01-25 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_driver'),
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
