# Generated by Django 6.0.1 on 2026-01-15 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_route_id', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('from_location', models.CharField(max_length=200, verbose_name='From')),
                ('to_location', models.CharField(max_length=200, verbose_name='To')),
                ('meta_title', models.CharField(max_length=200)),
                ('meta_description', models.TextField()),
                ('hero_title', models.CharField(max_length=300)),
                ('subheadline', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('distance', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('sedan_price', models.CharField(max_length=50)),
                ('van_price', models.CharField(max_length=50)),
                ('what_makes_better', models.JSONField(blank=True, default=list)),
                ('whats_included', models.JSONField(default=list)),
                ('destination_highlights', models.JSONField(blank=True, default=list)),
                ('ideal_for', models.JSONField(blank=True, default=list)),
                ('image', models.CharField(max_length=500)),
                ('book_href', models.CharField(max_length=500)),
                ('book_cta_label', models.CharField(max_length=100)),
                ('book_cta_support', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Route Detail',
                'verbose_name_plural': 'Route Details',
            },
        ),
        migrations.CreateModel(
            name='RouteFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq', to='routes.routedetail')),
            ],
            options={
                'verbose_name': 'Route FAQ',
                'verbose_name_plural': 'Route FAQs',
            },
        ),
        migrations.CreateModel(
            name='VehicleOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('Standard Car', 'Standard Car'), ('Minivan', 'Minivan')], max_length=100)),
                ('max_passengers', models.IntegerField()),
                ('ideal_for', models.CharField(max_length=200)),
                ('fixed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_options', to='routes.routedetail')),
            ],
            options={
                'verbose_name': 'Vehicle Option',
                'verbose_name_plural': 'Vehicle Options',
            },
        ),
    ]
