# Generated by Django 6.0.1 on 2026-01-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routedetail',
            name='image',
            field=models.ImageField(upload_to='Route Images'),
        ),
    ]
