# Generated by Django 6.0.1 on 2026-01-24 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_vehicle_fixed_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='booking_route_id',
            new_name='route_id',
        ),
    ]
