# Generated by Django 6.0.1 on 2026-01-23 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_routedetail_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RouteDetail',
            new_name='Route',
        ),
        migrations.RenameModel(
            old_name='VehicleOption',
            new_name='Vehicle',
        ),
    ]
