# Generated by Django 6.0.1 on 2026-01-25 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_rename_booking_route_id_route_route_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routefaq',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='routes.route'),
        ),
    ]
