# Generated by Django 6.0.1 on 2026-01-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_rename_routedetail_route_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='book_href',
            new_name='sub_headline',
        ),
        migrations.RemoveField(
            model_name='route',
            name='subheadline',
        ),
        migrations.AlterField(
            model_name='route',
            name='sedan_price',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='route',
            name='van_price',
            field=models.IntegerField(),
        ),
    ]
