# Generated by Django 6.0.1 on 2026-01-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_route_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Duration of the route in minutes (used for availability calculation)'),
        ),
    ]
