# Generated by Django 6.0.1 on 2026-01-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_route_duration_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('sedan', 'sedan'), ('vclass', 'vclass')], max_length=100),
        ),
    ]
