# Generated by Django 6.0.1 on 2026-01-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_alter_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='book_cta_label',
            field=models.CharField(max_length=300),
        ),
    ]
