# Generated by Django 6.0.1 on 2026-02-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_alter_route_book_cta_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='cross_border_information',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='route',
            name='reminder',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='route',
            name='whats_included',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
