# Generated by Django 6.0.1 on 2026-04-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0009_route_cross_border_information_route_reminder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='cash_deposit_percent',
            field=models.IntegerField(default=0),
        ),
    ]
