# Generated by Django 6.0.1 on 2026-01-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=30)),
                ('vehicle_type', models.CharField(choices=[('Sedan', 'Sedan'), ('Minivan', 'Minivan'), ('SUV', 'SUV'), ('Luxury', 'Luxury')], max_length=20)),
                ('max_passengers', models.PositiveIntegerField()),
                ('max_luggage', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('In Service', 'In Service'), ('Maintenance', 'Maintenance'), ('Out of Service', 'Out of Service')], default='Available', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('insurance_number', models.CharField(blank=True, max_length=50)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='vehicle_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-created_at'],
            },
        ),
    ]
