# Generated by Django 6.0.1 on 2026-01-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='image',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='insurance_expiry',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='insurance_number',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='max_luggage',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Minivan', 'Minivan')], default='Sedan', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Assigned', 'Assigned'), ('In Service', 'In Service'), ('Maintenance', 'Maintenance'), ('Out of Service', 'Out of Service')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
