# Generated by Django 6.0.1 on 2026-01-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_remove_vehicle_status_vehicle_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
