# Generated by Django 6.0.1 on 2026-01-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_alter_vehicle_license_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('sedan', 'sedan'), ('vclass', 'vclass')], default='Sedan', max_length=20),
        ),
    ]
