# Generated by Django 6.0.1 on 2026-01-23 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0004_rename_book_href_route_sub_headline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=30)),
                ('additional_information', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=50)),
                ('adults', models.IntegerField(default=1)),
                ('children', models.IntegerField(blank=True, null=True)),
                ('luggage', models.CharField(choices=[('Hand luggage only', 'Hand luggage only'), ('Medium (1–2 suitcases)', 'Medium (1–2 suitcases)'), ('Large (3–4 suitcases)', 'Large (3–4 suitcases)'), ('Extra large (5+ suitcases)', 'Extra large (5+ suitcases)')], max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed')], max_length=15)),
                ('payment_type', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed')], max_length=15)),
                ('payment_id', models.CharField(blank=True, max_length=25, null=True)),
                ('trip_type', models.CharField(choices=[('One Way', 'One Way'), ('Return', 'Return')], max_length=15)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('time_period', models.CharField(choices=[('Day Tariff', 'Day Tariff'), ('Night Tariff', 'Night Tariff')], max_length=15)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('return_time', models.TimeField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.route')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.vehicle')),
                ('passenger_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.passengerdetail')),
                ('transfer_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.transferinformation')),
            ],
        ),
    ]
