# Generated by Django 6.0.1 on 2026-01-24 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_options_booking_booking_id_and_more'),
        ('vehicle', '0002_remove_vehicle_image_remove_vehicle_insurance_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(choices=[('Standard Car', 'Standard Car'), ('Minivan', 'Minivan')], default='Standard Car', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], default='Card', max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.vehicle'),
        ),
    ]
