# Generated by Django 6.0.1 on 2026-01-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferinformation',
            name='luggage',
            field=models.CharField(choices=[('Hand', 'Hand'), ('Medium', 'Medium'), ('large', 'large'), ('Extra Large', 'Extra Large')], max_length=80),
        ),
    ]
