# Generated by Django 6.0.1 on 2026-01-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_transferinformation_luggage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('V Class', 'V Class')], default='Standard Car', max_length=100),
        ),
        migrations.AlterField(
            model_name='transferinformation',
            name='luggage',
            field=models.CharField(choices=[('Hand', 'Hand'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra Large', 'Extra Large')], max_length=80),
        ),
    ]
