# Generated by Django 6.0.1 on 2026-01-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(choices=[('sedan', 'sedan'), ('vclass', 'vclass')], default='Standard Car', max_length=100),
        ),
    ]
