# Generated by Django 6.0.1 on 2026-01-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_booking_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Paid 20%', 'Paid 20%')], max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(choices=[('sedan', 'sedan'), ('vclass', 'vclass')], max_length=100),
        ),
    ]
