# Generated by Django 6.0.1 on 2026-02-06 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='payment_id',
            new_name='transaction_id',
        ),
    ]
