# Generated by Django 6.0.1 on 2026-02-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_rename_payment_id_booking_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
