# Generated by Django 6.0.1 on 2026-02-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_booking_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'cash'), ('card', 'card')], max_length=15),
        ),
    ]
