# Generated by Django 6.0.1 on 2026-02-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_booking_payment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='price',
            new_name='amount_paid',
        ),
        migrations.AddField(
            model_name='booking',
            name='outstanding_amount',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
