# Generated by Django 6.0.1 on 2026-02-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_rename_price_booking_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='amount_paid',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='outstanding_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
