# Generated by Django 6.0.1 on 2026-02-07 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_booking_amount_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='status',
            new_name='booking_status',
        ),
    ]
