# Generated by Django 6.0.1 on 2026-02-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_rename_status_booking_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'paid'), ('paid 20%', 'paid 20%'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('expired', 'expired'), ('pending', 'pending')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
