# Generated by Django 6.0.1 on 2026-04-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_alter_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cash_deposit_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transferinformation',
            name='flight_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
