# Generated by Django 6.0.1 on 2026-04-08 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_booking_cash_deposit_percent_booking_created_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cash_deposit_percent',
        ),
    ]
