# Generated by Django 6.0.1 on 2026-01-27 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0004_alter_booking_driver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking_assigned', 'Booking Assigned'), ('booking_updated', 'Booking Updated'), ('booking_completed', 'Booking Completed'), ('booking_cancelled', 'Booking Cancelled'), ('vehicle_assigned', 'Vehicle Assigned'), ('schedule_change', 'Schedule Change'), ('general', 'General')], default='general', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_notifications', to='booking.booking')),
                ('driver', models.ForeignKey(limit_choices_to={'is_driver': True}, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver Notification',
                'verbose_name_plural': 'Driver Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
